apiVersion: v1
kind: Service
metadata:
  name: dev-position-service
  labels:
    app: dev-position-service
spec:
  type: NodePort
  ports:
    - port: 50005
      protocol: TCP
      targetPort: 50005
  selector:
    app: dev-position-service